version: "3.8"

services:
  vormi-portal-server:
    image: vormi-portal-server:latest
    container_name: vormi-portal-server
    restart: always
    networks:
      - vormi-portal-server-net
    expose:
      - "9682"
    ports:
      - "9682:9682"
    env_file:
      - "../.env"
    depends_on:
      - vormi-portal-server-postgres

  vormi-portal-server-postgres:
    image: postgres:latest
    container_name: vormi-portal-server-postgres
    environment:
      - POSTGRES_DB=vormi_portal_database
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - vormi-portal-server-net
    expose:
      - "5432"
    volumes:
      - vormi-portal-server-db-data-postgres:/var/lib/postgresql/data
      - vormi-portal-server-db-data-postgres-config:/var/lib/postgresql/dataConfig

networks:
  vormi-portal-server-net:
    driver: bridge

volumes:
  vormi-portal-server-db-data-postgres:
    driver: local

  vormi-portal-server-db-data-postgres-config:
    driver: local