#!/bin/bash

docker-compose -f ./vormi-portal-server/docker/docker-compose.yml down
docker volume rm docker_vormi-portal-server-db-data-postgres docker_vormi-portal-server-db-data-postgres-config
./gradlew vormi-portal-server:publishImageToLocalRegistry
docker-compose -f ./vormi-portal-server/docker/docker-compose.yml up